server:
    port: 9002
eureka:
    client:
        serviceUrl: 
            defaultZone: http://localhost:9000/eureka
spring:
    config:
        import: "optional:configserver:"
    application:
        name: tasks
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/tasks?serverTimezone=UTC
        username: root
        password: 
        nitialization-mode: always
    jpa:
        hibernate:
            ddl-auto: update